// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"cart/internal/cart/client/product_service"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewClientMock creates a new instance of ClientMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientMock {
	mock := &ClientMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ClientMock is an autogenerated mock type for the Client type
type ClientMock struct {
	mock.Mock
}

type ClientMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ClientMock) EXPECT() *ClientMock_Expecter {
	return &ClientMock_Expecter{mock: &_m.Mock}
}

// GetProduct provides a mock function for the type ClientMock
func (_mock *ClientMock) GetProduct(ctx context.Context, skuID int64) (*product_service.Product, error) {
	ret := _mock.Called(ctx, skuID)

	if len(ret) == 0 {
		panic("no return value specified for GetProduct")
	}

	var r0 *product_service.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*product_service.Product, error)); ok {
		return returnFunc(ctx, skuID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *product_service.Product); ok {
		r0 = returnFunc(ctx, skuID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*product_service.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, skuID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClientMock_GetProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProduct'
type ClientMock_GetProduct_Call struct {
	*mock.Call
}

// GetProduct is a helper method to define mock.On call
//   - ctx
//   - skuID
func (_e *ClientMock_Expecter) GetProduct(ctx interface{}, skuID interface{}) *ClientMock_GetProduct_Call {
	return &ClientMock_GetProduct_Call{Call: _e.mock.On("GetProduct", ctx, skuID)}
}

func (_c *ClientMock_GetProduct_Call) Run(run func(ctx context.Context, skuID int64)) *ClientMock_GetProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *ClientMock_GetProduct_Call) Return(product *product_service.Product, err error) *ClientMock_GetProduct_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *ClientMock_GetProduct_Call) RunAndReturn(run func(ctx context.Context, skuID int64) (*product_service.Product, error)) *ClientMock_GetProduct_Call {
	_c.Call.Return(run)
	return _c
}
